src/Entity/Project.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Repository\ProjectRepository;
use App\Workflow\IProjectWorkflow;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Survos\MeiliBundle\Api\Filter\FacetsFieldSearchFilter;
use Survos\MeiliBundle\Metadata\MeiliIndex;
use Survos\StateBundle\Traits\MarkingInterface;
use Survos\StateBundle\Traits\MarkingTrait;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
#[ApiResource(
    // ugh, used for meili
    normalizationContext: [
        'groups' => ['project.read', 'rp','translation','marking','_translations'],
    ],
    operations: [
        new Get(
            normalizationContext: ['groups' => ['project.read', 'marking']],
        ),
        new GetCollection(
            normalizationContext: ['groups' => ['project.read', 'marking']],
        )
    ]
)]
#[ApiFilter(OrderFilter::class, properties: ['marking', 'name'], arguments: ['orderParameterName' => 'order'])]
#[ApiFilter(SearchFilter::class, properties: ['marking' => 'exact', 'name' => 'partial'])]
#[ApiFilter(FacetsFieldSearchFilter::class,
    properties: ['tags', 'license','dependencies','extensions','minimumStability'])]
#[MeiliIndex(
    filterable: ['minimumStability'],
)]
class Project implements \Stringable, MarkingInterface
{
    use MarkingTrait;

    public function __construct()
    {
        $this->marking = IProjectWorkflow::PLACE_NEW;
    }

    // virtual properties

    #[Groups(['project.read'])]
    public ?string $license {
        get => $this->composerJson['license']??null;
    }

    #[Groups(['project.read'])]
    public array $tags {
        get => $this->composerJson['keywords']??[];
    }

    #[Groups(['project.read'])]
    public array $dependencies {
        get => array_values(array_filter(array_keys($this->composerJson['require']??[]), fn(string $key) => str_contains($key, '/')));
    }

    #[Groups(['project.read'])]
    public array $extensions {
        get => array_values(array_filter(array_keys($this->composerJson['require']??[]), fn(string $key) => str_starts_with($key, 'ext-')));
    }

    #[ORM\Id]
    #[ORM\GeneratedValue()]
    #[ORM\Column]
    #[Groups(['project.read'])]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?array $appJson = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['project.read'])]
    private ?array $composerJson = null;

    #[ORM\Column(nullable: true)]
    private ?array $pwaYaml = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $localDir = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $description = null;

    #[ORM\Column(length: 6, nullable: true)]
    private ?string $minimumStability = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $lastUpdatedTime = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAppJson(): ?array
    {
        return $this->appJson;
    }

    #[Groups(['project.read'])]
    public function setAppJson(?array $appJson): static
    {
        $this->appJson = $appJson;
        $this->description = $appJson['description'] ?? null;

        return $this;
    }

    public function getComposerJson(): ?array
    {
        return $this->composerJson;
    }

    public function setComposerJson(?array $composerJson): static
    {
        $this->composerJson = $composerJson;

        return $this;
    }

    public function getPwaYaml(): ?array
    {
        return $this->pwaYaml;
    }

    public function setPwaYaml(?array $pwaYaml): static
    {
        $this->pwaYaml = $pwaYaml;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    #[Groups(['project.read'])]
    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    #[Groups(['project.read'])]
    public function getLiveUrl(): string
    {
        return sprintf("https://%s.survos.com", $this->getName());
    }

    public function getRequireByOwner()
    {
        foreach ($this->getComposerJson()['require'] as $packageName=>$version) {
            if (str_contains($packageName, '/')) {
                [$owner, $name] = explode('/', $packageName);
                if (in_array($owner, ['symfony','twig', 'doctrine','phpdocumentor','phpstan'])) {
                    continue;
                }
                $owners[$owner][] = [
                    'display' => $name, // str_replace('-bundle', '-b', $name),
                    'package' => $packageName
                    ];
            }
        }
        return $owners;

    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    #[Groups(['project.read'])]
    public function getGithubUrl(): string
    {
        return sprintf("https://github.com/%s", $this->getComposerJson()['name']??'!!');

    }

    public function getLocalDir(): ?string
    {
        return $this->localDir;
    }

    public function setLocalDir(?string $localDir): static
    {
        $this->localDir = $localDir;

        return $this;
    }

    #[Groups(['project.read'])]
    public function getMinimumStability(): ?string
    {
        return $this->minimumStability;
    }

    public function setMinimumStability(?string $minimumStability): static
    {
        $this->minimumStability = $minimumStability;

        return $this;
    }

    public function getLastUpdatedTime(): ?\DateTimeImmutable
    {
        return $this->lastUpdatedTime;
    }

    public function setLastUpdatedTime(?\DateTimeImmutable $lastUpdatedTime): static
    {
        $this->lastUpdatedTime = $lastUpdatedTime;

        return $this;
    }
}

src/Entity/Show.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Repository\ShowRepository;
use App\Workflow\ShowWFDefinition;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Survos\StateBundle\Traits\MarkingInterface;
use Survos\StateBundle\Traits\MarkingTrait;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: ShowRepository::class)]
#[ApiResource(
    // ugh, used for meili
    normalizationContext: [
        'groups' => ['show.read', 'rp','translation','marking','_translations'],
    ],
    operations: [
        new Get(
            normalizationContext: ['groups' => ['show.read', 'marking']],
        ),
        new GetCollection(
            normalizationContext: ['groups' => ['show.read', 'marking']],
        )
    ]
)]
#[Groups(['show.read'])]
class Show implements MarkingInterface, \Stringable
{
    use MarkingTrait;
    public function __construct(
        #[ORM\Id] #[ORM\Column]
        private readonly ?string $code = null
)
    {
        $this->marking = ShowWFDefinition::PLACE_NEW;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function getLines(): array
    {
        return explode("\n", $this->getAsciiCast());
    }

    public function getHeader(): ?array
    {
        return json_decode($this->getLines()[0], true);
    }


    #[ORM\Column(length: 255, nullable: true)]
    public ?string $title = null;

    #[ORM\Column(nullable: true)]
    public ?string $author = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $asciiCast = null;

    #[ORM\Column(nullable: true)]
    public ?int $fileSize = null;

    #[ORM\Column(nullable: true)]
    public ?int $asciinamaId = null;

    public ?string $castUrl { get => $this->asciinamaId ? 'https://asciinema.org/a/' . $this->asciinamaId : null; }
    public ?string $downloadUrl { get => $this->asciinamaId ? 'https://asciinema.org/a/' . $this->asciinamaId  . '.cast': null; }



//    #[ORM\Column]
//    #[ApiProperty("duration in seconds")]
//    public ?int $duration = null;

    #[ORM\Column]
    public ?int $markerCount = null;

    #[ORM\Column]
    public ?int $lineCount = null;

    #[ORM\Column(nullable: true)]
    #[ApiProperty("the number of type 'i' in the file")]
    public int $inputCount = 0;

    #[ORM\Column]
    public ?float $totalTime = null;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAsciiCast(): ?string
    {
        return $this->asciiCast;
    }

    public function setAsciiCast(string $asciiCast): static
    {
        $this->asciiCast = $asciiCast;

        return $this;
    }

    public function getFileSize(): ?int
    {
        return $this->fileSize;
    }

    public function setFileSize(int $fileSize): static
    {
        $this->fileSize = $fileSize;

        return $this;
    }

    public function getMarkerCount(): ?int
    {
        return $this->markerCount;
    }

    public function setMarkerCount(int $markerCount): static
    {
        $this->markerCount = $markerCount;

        return $this;
    }

    public function getLineCount(): ?int
    {
        return $this->lineCount;
    }

    public function setLineCount(int $lineCount): static
    {
        $this->lineCount = $lineCount;

        return $this;
    }

    public function getTotalTime(): ?float
    {
        return $this->totalTime;
    }

    public function setTotalTime(float $totalTime): static
    {
        $this->totalTime = $totalTime;

        return $this;
    }

    public function __toString()
    {
        return $this->code;
    }
}

templates/base.html.twig
{% extends "layout.html.twig" %}
{% set appShortName = 'KPA' %}
{% block logo_mini 'KPA' %}

     {% block stylesheets %}
         <link rel="stylesheet" type="text/css" href="{{ asset('bundles/survosmeili/style.css') }}">
         <link rel="stylesheet" type="text/css" href="{{ asset('bundles/survosbootstrap/bootstrap/style.css') }}">

         {{ parent() }}
     {% endblock %}

    {% block javascripts %}
        {% block importmap %}{{ importmap('app') }}{% endblock %}
        {{ parent() }}
    {% endblock %}

templates/blank.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{{ _self }}
{% endblock %}

{% block title %}

{% endblock %}

templates/cine-data.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ dump(data.header) }}

    {% for line in data.lines %}
        <li>
            {{ dump(line) }}
        </li>
    {% endfor %}
{% endblock %}

{% block title %}

{% endblock %}

templates/cine.html.twig
{% extends 'base.html.twig' %}

{% block title %}Playing {{ castCode }}{% endblock %}
{% block page_header %}Playing {{ castCode }}{% endblock %}
{% block nav '' %}
{# {% block stylesheets %} #}
{# {{ parent() }} #}
{# {{ ansi_css }} #}
{# {% endblock %} #}
{% block raw_bodyXX %}
    <body>
    <a href="{{ path('app_cine', {cineCode: castCode}) }}" target="_blank">
        JSON
    </a>

    IMAGES
    {% set thumb = asset('2025-05-25-09-22-11.png') | imagine_filter('large') %}
    {#    {% set thumb = asset('2025-05-25-09-22-11.png') | imagine_filter_cache('small')  %} #}
    <a href="{{ thumb }}" target="_blank">
        {#        <img src="{{thumb }}" /> #}
        Thumb
    </a>

    {{ block('player') }}

    </body>
{% endblock %}

{% block body %}
    <a href="{{ path('app_cine', {cineCode: castCode}) }}" target="_blank">
        JSON
    </a>

    IMAGES
    {% set thumb = asset('2025-05-25-09-22-11.png') | imagine_filter('large') %}
    {#    {% set thumb = asset('2025-05-25-09-22-11.png') | imagine_filter_cache('small')  %} #}
    <a href="{{ thumb }}" target="_blank">
        {#        <img src="{{thumb }}" /> #}
        Thumb
    </a>

{#    {{ block('player') }}#}

{% endblock %}
{% block player %}
    {% set _sc = 'player' %}
    <div class="row" {{ stimulus_controller(_sc, {
        code: castCode,
        url: path('ciine_data', {cineCode: castCode, _format: original ? 'cast': 'txt'})
    }) }}>
        <div class="col-md-8">
            <div>
                <h1 {{ stimulus_target(_sc, 'marker') }}>
                    marker text
                </h1>
                <!-- ... -->
                <div {{ stimulus_target(_sc, 'player') }}>

                </div>
            </div>
        </div>
        <div class="col-md-4">
            <h3>{{ markers|default([])|length }} Markers</h3>
            {% for m in markers|default([]) %}
                <li>
                    <a {{ stimulus_action(_sc, 'seek', null, {timestamp: m[0]}) }}>
                        M {{ ux_icon('play') }} @ {{ m[0]|number_format(1) }}
                    </a>

                    {#                    <pre> #}
                    {#                    {{ m[1]|ansi_to_html }}</li> #}
                    {#                    </pre> #}
                    {{ (m[1]|ansi_to_html)|raw }}
                </li>
            {% endfor %}
            <div class="scrollable-container" data-controller="scrollable">
                <div id="scrollable-content">
                    <!-- Your content here -->
                    <table>
                        <thead>
                        <tr>
                            <th>Running</th>
                            <th>Int</th>
                            <th>Text</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% set elapsedTime = 0 %}
                        {% for l in jsonCast.lines %}
                            {% set elapsedTime = elapsedTime + l[0] %}
                            <tr>
                                <td>
                                    {{ elapsedTime|number_format(1) }}
                                </td>
                                <td>
                                    <a title="{{ l[0]|number_format(2) }}" {{ stimulus_action(_sc, 'seek', null, {timestamp: elapsedTime}) }}>

                                        {{ ux_icon('play') }}
                                    </a>
                                </td>
                                <td>
                                    {{ l[2]|ansi_to_html }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {#            {{ jsonCast|json_pretty }} #}
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/controller.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <pre>{{ ns }}</pre>

{% endblock %}

templates/home.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <h3>Files (*.casts)</h3>
    {% for cast in casts %}
        <li>
            {{ cast }}
            <a href="{{ path('app_player', {cineCode: cast.basename|replace({'.cast': ''})}) }}">
                {{ cast.basename }}
            </a>
        </li>
    {% endfor %}

    <hr />


    <h3>Shows in Database</h3>
    {% for show in shows %}
    <li>
        <a href="{{ path('app_player', {cineCode: show.code}) }}">
        <code>{{ show.code }}</code>
        <b>{{ show.title }}</b>
            {{ show.lineCount }}
            {{ show.fileSize }}
        </a>

        @Asci: <a href="{{ show.castUrl }}" target="_blank">{{ show.castUrl }}</a>

        original .cast:
        <a href="{{ path('app_player', {cineCode: show.code, _format: 'cast'}) }}">
            Play
        </a>
        <a href="{{ path('ciine_data', {cineCode: show.code, _format: 'cast'}) }}">
            show
        </a>

        DATA:
        {% for format in ['html','json','ndjson','cast','txt'] %}
            <a href="{{ path('ciine_data', {cineCode: show.code, _format: format}) }}">
                {{ format }}
            </a>

        {% endfor %}
    </li>
    {% endfor %}
    <h3>{{ running|length }} Running Projects</h3>

    <div class="row" data-masonry='{"percentPosition": true }'>

        {% if runningOnly %}
        <div class="container-xl">
            <div class="row row-cards">
                {% for project in running   %}
                    <div class="col-sm-6 col-lg-4">
                        <div class="card card-sm">
                            {% set imageUrl = "%s.wip.png"|format(project.name) %}


{#                            <a href="#" class="d-block"><img src="./static/photos/beautiful-blonde-woman-relaxing-with-a-can-of-coke-on-a-tree-stump-by-the-beach.jpg" class="card-img-top"></a>#}
                                <div class="card-body">
                                    <div class="d-flex align-items-center">
{#                                        <span class="avatar avatar-2 me-3 rounded" style="background-image: url(./static/avatars/000m.jpg)"> </span>#}
                                        <div>
                                            <div>
                                                <a target="_blank" href="{{ project.githubUrl }}" class="text-secondary">
                                                    <twig:ux:icon name="mdi:github" />
                                                    {#                                                {{ project.composerJson.name??project.name }}#}
                                                    {#                                {{ project.appJson.repository|replace({'https://github.com/': ''}) }}#}
                                                </a>
                                                {{ project.composerJson.name??project.name }}
                                            </div>
                                            {% set liveUrl = "https://%s.wip"|format(project.name) %}
                                            <div class="text-secondary"><a href="{{ liveUrl }}" target="_blank">{{ liveUrl }}</a></div>
                                        </div>
                                    </div>
                                    <a href="{{ path('project_show', {id: project.id}) }}" class="d-block">
                                        <img class="card-img-top" src="{{ imageUrl }}" class="card-img-top">
                                    </a>

                                </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <h3>All Projects</h3>
        {% for project in projects %}
            <div class="grid-item col-sm-6  col-lg-3">
                {% with { project: project } %}
                    <twig:card :title="project.name">
                        <twig:block name="title">
                            <h2>
                                <a target="_blank" href="{{ project.githubUrl }}">
                                    <twig:ux:icon name="mdi:github" />
                                    {{ project.composerJson.name??project.name }}
                                    {#                                {{ project.appJson.repository|replace({'https://github.com/': ''}) }}#}
                                </a>
                            </h2>
                            {% set imageUrl = "%s.wip"|format(project.name) %}
                            <img src="{{ imageUrl }}.png" />
                            {{ imageUrl }}

                        </twig:block>

                        <twig:block name="card_title">
                            <h1>
                                <a href="https://{{ project.code }}.wip">
                                    {{ project.code }}
                                </a>
                                {{ project.composerJson.name??project.name }}
                            </h1>
                            {{ project.githubUrl }}
                            <a target="_blank" href="{{ project.appJson.repository }}">
                                <twig:ux:icon name="mdi:github" />
                                {#                                {{ project.appJson.repository|replace({'https://github.com/': ''}) }}#}
                            </a>
                        </twig:block>
                        <twig:block name="card_body">
                            {{ project.composerJson.description|default('missing!') }}
                            &nbsp;
                        </twig:block>
                        <twig:block name="links">
                        </twig:block>
                        <twig:block name="footer">
                            {{ project.status }}
                            <a href="{{ path('project_show', {id: project.id}) }}">Show</a>
                            <a href="{{ project.liveUrl }}" target="_blank">
                                {{ project.liveUrl }}
                            </a>
                            <a href="https://{{ project.name }}.wip" target="_blank">
                                {{ project.name }}.wip
                            </a>
                        </twig:block>

                    </twig:card>
                    {#                {{ block('card') }}#}
                {% endwith %}
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/layout.html.twig
{% extends "@SurvosBootstrap/%s/base.html.twig"|format(theme_option('theme')) %}

    {% block stylesheets %}
        {#        <link rel="stylesheet" href="https://kit.fontawesome.com/821a06d4ef.css" crossorigin="anonymous">#}
{#        <link rel="stylesheet" type="text/css" href="{{ asset('bundles/survosapigrid/style.css') }}" ></link>#}
{#        <link rel="stylesheet" type="text/css" href="{{ asset('bundles/survosbootstrap/bootstrap/style.css') }}">#}

        {{ parent() }}
    {% endblock %}


{% block description "Survos Showcase" %}


{% set appShortName = 'Showcase' %}


{% block logo_mini %}<b>KPA</b>{% endblock %}
{% block logo_large '<b>KPA</b> Admin' %}

{% block page_title 'KPA Admin' %}
{% block page_subtitle 'Songs and Music!' %}

{#    {% block stylesheets %}#}
{#        {{ parent() }}#}
{#    {% endblock %}#}

    {% block javascripts %}
        {{ parent() }}
    {% endblock %}


{# could also overwrite template
        {% include '@SurvosBootstrapBundle/Partials/_footer.html.twig' %}
#}

{#{% block footer %}#}
{#    FOOTER {{ _self }}#}
{#    <footer class="main-footer">#}
{#        Theme: {{ theme_option('theme') }}#}
{#        <!-- To the right -->#}
{#        <div class="pull-right hidden-xs">#}

{#        </div>#}
{#        <!-- Default to the left -->#}
{#        <strong>Data Copyright &copy; 2020 <a href="#">Kid Pan Alley</a>.</strong>  All rights reserved.#}
{#        <strong>Code Copyright &copy; 2020 <a href="#">Survos</a>.</strong>  All rights reserved.#}
{#    </footer>#}
{#{% endblock %}#}

{#{% block body %}#}
{#    <h1>XX</h1>#}
{#    {{ block('page_content') }}#}
{#{% endblock %}#}

templates/show.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <h1>{{ project.name }}</h1>

    {{ project.liveUrl }}


    {% for owner, req in project.requireByOwner %}
        <ul>
            <li>
                {{ owner }}/
                <ul>
                {% for r in req %}
                <li>
                    {{ r.display }}
                    {#  description would be really cool here!  Link to repo? #}
{#                    {{ r.package }}#}
                </li>
            {% endfor %}
                </ul>
            </li>
        </ul>
    {% endfor %}

    <h2>PWA</h2>
    {{ project.pwaYaml|json_pretty }}

    <h2>AppJson</h2>
    {{ project.appJson|json_pretty }}
{% endblock %}